---
crate:
  manifest-path: ./rust/Cargo.toml

ios:
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim

android:
  targets:
    - aarch64-linux-android
    - armv7-linux-androideabi
    - x86_64-linux-android
